tools = [{
    "type": "function",
    "function": {
        "name": "list_id_of_type",
        "description": "get all element id of one specific type",
        "parameters": {
            "type": "object",
            "properties": {
                "graph_name": {
                    "type": "string",
                    "enum": ['http://example.com/landuse', 'http://example.com/soil',
                             'http://example.com/buildings'],
                    "description": f"the graph user wants to search in database, you need to select the one has most "
                                   f"similar semantic meaning",
                },
                "single_type": {
                    "type": "string",
                    "description": "type of data user want to search",
                },

            },
            "required": ["graph_name", "type_name"]
        },
    }
},
    {
        "type": "function",
        "function": {
            "name": "list_type_of_graph_name",
            "description": "get all element types of this graph and return a type_list, example: for soil graph, "
                           "its type_list gonna be different kinds of soil",
            "parameters": {
                "type": "object",
                "properties": {
                    "graph_name": {
                        "type": "string",
                        "enum": ['http://example.com/landuse', 'http://example.com/soil',
                                 'http://example.com/buildings'],
                        "description": f"the graph user wants to search in database, you need to select the one has "
                                       f"most similar semantic meaning",
                    },

                },
                "required": ["graph_name"],
            },
        }
    },

    {
        "type": "function",
        "function": {
            "name": "find_bounding_box",
            "description": "If user wants to get query result from a specific location, you need to first run this "
                           "function with argument region_name, then the other function would limit its result in "
                           "this region automatically (you don't need to add region name to other function). Example: "
                           "if user wants to search result from munich germany, input of this function would be ["
                           "'munich germany'].",

            "parameters": {
                "type": "object",
                "properties": {
                    "region_name": {
                        "type": "string",
                        "description": f"the region name you want to search",
                    },

                },
                "required": ["region_name"],
            },
        }
    },
    {
        "type": "function",
        "function": {
            "name": "geo_calculate",
            "description": "geo_calculate function has functions: contains, intersects, buffer. Input should be two "
                           "id_list which generated by function list_id_of_type and function name you want to use. ",

            "parameters": {
                "type": "object",
                "properties": {
                    "subject_variable": {
                        "type": "string",
                        "description": f"the subject variable name in search",
                    },
                    "object_variable": {
                        "type": "string",
                        "description": f"the object variable name in search",
                    },
                    "function_name": {
                        "type": "string",
                        "enum": ['contains', 'intersects',
                                 'buffer'],
                        "description": f"the geo relationship user wants to search.",
                    },
                    "buffer_number": {
                        "type": "int",
                        "description": f"if the geo relationship user asked is about buffer area, then you need to "
                                       f"input a integer value as "
                                       f"buffer_number.",
                    },

                },
                "required": ["id_list_1", 'id_list_2', 'function_name'],
            },
        }
    },

]
